### ISSUE TITLE
Decide where to move the Element Definition creator to. 

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#355]
Decide where to move the Element Definition creator to. Maybe another page should be created?
Related to #352

**Comment by samatrhea** [comment]
I think we need to create a dedicated page for this. That page will be a new application because we enter into populating a model with new items. This page/app should allow a user to:
  - add/edit/delete new element definitions via details panel editor
  - add/edit/delete new element usages -  by means of drag-n-drop and details panel editor
  - add/edit/delete new parameters by means of drag-n-drop for the parameter-type browser and via details panel editor
  - drag-n-drop from a catalogue (bi-directional)
  

we've noticed in the desktop app that having 2 Element Definition browsers open to support the creation of usages etc. is very beneficial. So, i think we need to support that here as well. see image below as proposal:

 ![comet](https://user-images.githubusercontent.com/22165725/233927603-72f5cb47-54db-4305-abca-8747fefbdbab.png)

**Comment by antoineatrhea** [comment]
I agree on the creation of a new app to handle that.
